# Generated by Django 3.2.8 on 2021-10-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rpc', models.TextField(max_length=512)),
                ('url', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
            ],
        ),
    ]
