# Generated by Django 3.2.8 on 2021-10-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211014_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='posted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='through_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
