# Generated by Django 3.2.8 on 2021-10-14 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_vacancy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='posted_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='through_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
